WIP - refactoring current REST API and adding new endpoint
openedx/credentials pull request #1702
Opened 2022-07-14 19:07 UTC by MaxFrank13

This PR is a part of a larger task for migrating to the new Learner Record MFE. 

An `api.py` file has been created in the `records` directory to house re-usable functions employed by both the REST API and legacy frontend. The `get_record_data` function has been moved to `api.py` from `credentials/apps/records/views.py`.

The REST API has been refactored to use a ViewSet instead of the APIView it employed previously. A router has also been added to `urls.py` in the `rest-api/v1` directory as well as a serializer called `ProgramRecordSerializer`.

Unit tests have been added to test any new code. There are comments detailing some of my thought process but also posing questions for anyone who is reviewing. This is still a WIP as I am anticipating the need to address some general housekeeping issues or perhaps add more tests.

2022-07-14 19:07 UTC, openedx-webhooks commented
Thanks for the pull request, @MaxFrank13!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

<!-- comment:no_cla -->


<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2022-07-14 20:04 UTC, justinhynes commented on credentials/apps/records/api.py
> +    program = Program.objects.prefetch_related("course_runs__course").get(uuid=program_uuid, site=site)
The Program model here is coming from a Django app outside of the Records app itself. We shouldn't be importing and using the model directly. This breaks boundaries between the apps themselves.

Instead, we should be adding a new Python API function in the `catalog` app's public `api.py` that returns program information. 

You can read more about how we'd like to structure our Django apps in OEP-49: https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0049-django-app-patterns.html

2022-07-14 20:06 UTC, justinhynes commented on credentials/apps/records/api.py
> +    program = Program.objects.prefetch_related("course_runs__course").get(uuid=program_uuid, site=site)
Also wanted to mention, I know that you are refactoring this from existing code and the sins of your predecessors are not _your_ fault. We have a chance to make it right here, so we should be able to take a little bit of extra time to make it right. :)

2022-07-14 20:10 UTC, justinhynes commented on credentials/apps/records/api.py
> +        UserCredential.objects.filter(
Similar to my above comment, the `UserCredential` app is part of the `credentials` Django app and shouldn't be imported and used directly here. 

From a quick glance, there is already a function in the `credentials` app's public `api.py` called `get_user_credentials_by_content_type`. We might be able to use this instead over interacting with the model directly.

2022-07-14 20:11 UTC, justinhynes commented on credentials/apps/records/api.py
> +        )
Same here; can we use the `get_user_credentials_by_content_type` function here?

2022-07-14 20:14 UTC, justinhynes commented on credentials/apps/records/api.py
> +            if user_credential.status == UserCredential.AWARDED:
Same here; We don't want to use the UserCredential model, or any of its attributes/methods here in this file directly. 

The `credentials` Django app has an enum named `UserCredentialStatus` in it's `data.py` file. These `data.py` files are also public and can be imported across Django apps. Let's import that enum and use that instead.

2022-07-14 20:16 UTC, justinhynes commented on credentials/apps/records/api.py
> +def get_record_data(user, program_uuid, site, platform_name=None):
Overall, this is a very big and complicated function. Maybe we can think about a way to break this up better so it's easier to follow and grok.

2022-07-14 20:17 UTC, justinhynes commented on credentials/apps/records/api.py
> +        uuid(ID): ID associated with this run of the program
Nit: I think we should update the documentation here to include the other arguments. It looks like it only has the `uuid` argument, but there are three more being passed into this function.

2022-07-15 11:54 UTC, justinhynes commented on credentials/apps/records/api.py
> +    program_list_url = "/records/"
Does this need to be part of this function? I am under the impression that this data/url is important to the legacy frontend/template, but I don't think the MFE would use it. Is there any way to move this out?

2022-07-15 11:56 UTC, justinhynes commented on credentials/apps/records/rest_api/v1/tests/test_serializers.py
> +        import pdb; pdb.set_trace()
Please make sure to remove this line.

2022-07-15 11:57 UTC, justinhynes commented on credentials/apps/records/rest_api/v1/tests/test_serializers.py
> +        # self.assertEqual(serializer["record"]["platform_name"], expected["record"]["platform_name"])
Is this supposed to be commented out?

2022-07-15 11:59 UTC, justinhynes commented on credentials/apps/records/rest_api/v1/urls.py
> +]
You can replace this line here with:
`urlpatterns += router.urls`

2022-07-15 12:00 UTC, justinhynes commented on credentials/apps/records/rest_api/v1/views.py
> -        GET: /records/api/v1/program_records/
We should still include this line for easy discoverability of the REST API path.

2022-07-15 12:01 UTC, justinhynes commented on credentials/apps/records/rest_api/v1/views.py
> +        Retrieve data for all the user's enrolled programs
I think this comment should be updated, it looks like it may be copy-pasta. It should be updated to say that it's retrieveing data for a specific program a learner is enrolled in. 

Could we also include the path to the REST API? (/records/api/v1/program_records/<program_uuid>/)

2022-07-15 12:02 UTC, justinhynes commented on credentials/apps/records/rest_api/v1/views.py
> +        # import pdb; pdb.set_trace()
Please make sure to remove any commented out lines we don't need.

2022-07-15 12:06 UTC, justinhynes commented on credentials/apps/records/rest_api/v1/tests/test_views.py
> +import json
We're importing the `json` package here but I don't think I saw it used anywhere. Do we need still need this?

2022-07-15 12:19 UTC, justinhynes commented
Max, I think we're missing a piece of this refactor. You have refactored-and-moved the logic to retrieve program record data to the records app's `api.py`, but I think the template/legacy frontend could use some further refactoring.

It looks like we still have some duplicated logic in the `../credentials/apps/records/views.py::ProgramRecordView` class. (in the `_get_record()` function. It looks like we moved this to a `get_program_details` function in the `api.py` file. Would it be possible to refactor the code in the `ProgramRecordView` class to use your new function and cut down on the code duplication?

Thanks!

2022-07-15 12:28 UTC, justinhynes requested changes
Thanks for your work on this so far! There's a bit more work here before we can call ourselves done. Let me know if you have any questions about the comments I've left in the PR!

2022-07-18 18:54 UTC, MaxFrank13 commented on credentials/apps/records/rest_api/v1/tests/test_views.py
> +    def test_get_details(self):
When attempting to make a public request, the `get_program_details` function is looking for a `ProgramCertRecord` with that uuid. I am currently getting stuck on that 404 during my test. Do I need to add a mock of the `ProgramCertRecord` in the `setUp()` function in order for this test to work?

2022-07-22 14:13 UTC, justinhynes commented on credentials/apps/catalog/api.py
> +        uuid(ID): Program uuid to find by
Nit: What is an "ID"? Is this an actual object (which I may not be familiar with?)? Or would this be a UUID in the form of a string?

2022-07-22 14:14 UTC, justinhynes commented on credentials/apps/credentials/api.py
> +        program_uuid(ID): unique identifier for the desired program
Nit: Same question as the one above in the `../catalogs/api.py` file.

2022-07-22 14:14 UTC, MaxFrank13 commented on credentials/apps/catalog/api.py
> +        uuid(ID): Program uuid to find by
This is the uuid in the form of a string. Should the (ID) be (string)? or (str)?

2022-07-22 14:15 UTC, justinhynes commented on credentials/apps/records/api.py
> +    program = get_program_and_course_details(program_uuid, site)
Nit: Missing some function documentation here.

2022-07-22 14:20 UTC, justinhynes commented on credentials/apps/records/rest_api/v1/tests/test_serializers.py
> +                        "name": "Test çօմɾʂҽ iJXceupiNcKb",
This caught my eye. It looks like generated data from a factory/faker, or is this hard-coded into the setup data? Just wanted to confirm... would it matter anywhere if the name of the course changes anywhere? Could this cause a test to fail somehow?

2022-07-22 14:23 UTC, justinhynes commented on credentials/apps/catalog/api.py
> +        uuid(ID): Program uuid to find by
This should be `str` then.

2022-07-22 14:24 UTC, justinhynes approved these changes
A couple of nits mostly around documentation but it looks good overall! Thanks for your work on this. :)

2022-07-22 15:24 UTC, MaxFrank13 commented on credentials/apps/records/rest_api/v1/tests/test_serializers.py
> +                        "name": "Test çօմɾʂҽ iJXceupiNcKb",
Currently there is no test for the course name as it is used here in the serializer tests. In the views test, we are checking the `grades` field so I believe we've covered our backs on this one?

2022-07-25 17:09 UTC, merged

2022-07-25 17:09 UTC, openedx-webhooks commented
@MaxFrank13 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/credentials&entry.867055334=https://github.com/openedx/credentials/pull/1702&entry.1484655318=https://github.com/MaxFrank13&entry.752974735=2022-07-14+19:07&entry.1917517419=2022-07-25+17:09&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->