Add Backstage config
openedx/credentials pull request #1705
Opened 2022-07-22 15:25 UTC by hurtstotouchfire

hello world

2022-07-22 15:26 UTC, hurtstotouchfire commented on catalog-info.yml
> +  owner: 2u-aperture
@feanil does this naming convention seem reasonable for 2U?

2022-07-28 15:27 UTC, feanil commented on catalog-info.yml
> +  owner: 2u-aperture
Yea, I think this is great.  Ideally we create a corresponding github group so people can easily see who the members are.

2022-09-09 21:52 UTC, hurtstotouchfire commented on catalog-info.yml
> +  owner: 2u-aperture
We can either update https://github.com/orgs/openedx/teams/edx-aperture or create a new team. I pinged Ed on slack, but lmk if you want me to create a tCRIL ticket or just go ahead and update this team.

2022-09-09 22:57 UTC, nedbat commented on catalog-info.yml
> +    github.com/project-slug: openedx/Credentials
Where did this annotation come from? It's redundant with the repo name.

2022-09-09 22:57 UTC, nedbat commented on catalog-info.yml
> +
We should leave the explanatory comment at the top: it can help people spelunking around understand what this file is for.

2022-09-09 22:58 UTC, nedbat commented on catalog-info.yml
> +  owner: 2u-aperture
Is it possible to use a team in the edx org, or that won't work for pinging, etc?

2022-09-12 14:00 UTC, hurtstotouchfire commented on catalog-info.yml
> +
I didn't delete this, I just wrote it before it was in there. Can you add in any of the new comments you think are helpful?

2022-09-12 14:01 UTC, hurtstotouchfire commented on catalog-info.yml
> +    github.com/project-slug: openedx/Credentials
It was in the original template @feanil posted, so I'm honestly not sure, but I am fine with removing it.

2022-09-12 14:01 UTC, hurtstotouchfire commented on catalog-info.yml
> +      icon: 'Document'
```suggestion
      icon: 'Article'
```

2022-09-12 14:15 UTC, hurtstotouchfire commented on catalog-info.yml
> +  owner: 2u-aperture
I think it makes more sense for the teams to be administered by tCRIL.

2022-09-12 15:05 UTC, feanil commented on catalog-info.yml
> +    github.com/project-slug: openedx/Credentials
Can you link to the template you're basing this on? It isn't in the one provided here: https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055/decisions/0001-use-backstage-to-support-maintainers.html#references

It should not be needed.

2022-09-14 20:39 UTC, nedbat commented on catalog-info.yml
> +
Sorry, I didn't understand the evolution of this content.  I'll make some tweaks.

2022-09-14 20:43 UTC, nedbat requested changes

2022-09-14 20:43 UTC, nedbat commented on catalog-info.yml
> +
```suggestion
# This file records information about this repo. Its use is described in OEP-55:
# https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html
```

2022-09-14 20:43 UTC, nedbat commented on catalog-info.yml
> +    github.com/project-slug: openedx/Credentials
from [OEP-55/ADR-01](https://github.com/openedx/open-edx-proposals/blob/10abba68be201d42447fbf50dcfdd06a231e10a5/oeps/processes/oep-0055/decisions/0001-use-backstage-to-support-maintainers.rst):
```suggestion
  annotations:
    # (Optional) Annotation keys and values can be whatever you want.
    # We use it in Open edX repos to have a comma-separated list of GitHub user
    # names that might be interested in changes to the architecture of this
    # component.
    openedx.org/arch-interest-groups: ""
```

2022-09-15 19:00 UTC, hurtstotouchfire commented on catalog-info.yml
> +    github.com/project-slug: openedx/Credentials
I don't know, I just copied the original one you guys sent. If it's gone now nbd, we can delete it.

2022-09-15 19:01 UTC, hurtstotouchfire commented on catalog-info.yml
> +    github.com/project-slug: openedx/Credentials
Here it is: https://github.com/openedx/DoneXBlock/blob/master/catalog-info.yaml#L6

2022-09-15 19:41 UTC, nedbat commented on catalog-info.yml
> +  owner: group:openedx/2u-aperture
1) I was wrong, there shouldn't be an "openedx/" prefix on this.
2) The group has to be a team in the openedx GitHub organization.  Are we going to make the `2u-aperture` team there, or should this change to `credentials-maintainers`?

2022-09-19 16:22 UTC, hurtstotouchfire commented on catalog-info.yml
> +  owner: group:openedx/2u-aperture
Neither team currently exists but we can fix it when a team does exist. I'd like to see this in backstage, so I'm going to just merge shortly.

2022-09-19 17:10 UTC, nedbat commented on catalog-info.yml
> +  owner: group:openedx/2u-aperture
:+1:

2022-09-19 17:10 UTC, nedbat approved these changes

2022-09-21 17:01 UTC, feanil commented on catalog-info.yml
> +      icon: 'Code'
```suggestion
```
You don't need this because it's already auto-linked in backstage.

2022-09-27 16:47 UTC, hurtstotouchfire commented on catalog-info.yml
> +      icon: 'Code'
I've made this change.

2022-09-27 16:47 UTC, hurtstotouchfire commented on catalog-info.yml
> +# This file records information about this repo. Its use is described in OEP-55:
I've made this change.

2022-09-27 16:50 UTC, hurtstotouchfire commented on catalog-info.yml
> +  owner: group:openedx/2u-aperture
I just renamed the team in Github to `2U-aperture`.

2022-09-27 18:09 UTC, feanil approved these changes

2022-09-28 14:56 UTC, merged