docs: [FC-0002] Issue verifiable credentials to learners  ADR
openedx/credentials pull request #1846
Opened 2022-12-04 20:01 UTC by GlugovGrGlib

In this ADR you will find a proposal to implement Verifiable Credentials sharing mechanism according to [Verifiable Credentials design](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3490840577/Verifiable+Credentials+design).

This ADR is proposed as a part of [FC-0002](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3493822533/General+Design+for+Sharing+Open+edX+Credentials+-+FC-0002) General Design for Sharing Open edX Credentials

Ticket: https://github.com/openedx/credentials/issues/1735

This PR depends on, and should be merged after: https://github.com/openedx/credentials/pull/1797

2022-12-04 20:01 UTC, openedx-webhooks commented
Thanks for the pull request, @GlugovGrGlib!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-12-12 16:06 UTC, e0d requested changes
I've proposed a couple small changes and posed a couple bigger questions.  Overall I think both the ADRs are very strong, well researched, well documents, clearly written.

2022-12-12 16:06 UTC, e0d commented on docs/decisions/0007-verifiable-credentials-issuing.rst
> +* sing verifiable credentials with the library `didkit-python`_, the python bindings for the open-source Rust-based `DIDKit`_ library maintained by SpruceID.
```suggestion
* sign verifiable credentials with the library `didkit-python`_, the python bindings for the open-source Rust-based `DIDKit`_ library maintained by SpruceID.
```

2022-12-12 16:06 UTC, e0d commented on docs/decisions/0008-issue-verifiable-credentails-in-learner-records-mfe.rst
> +Learners can issue the same Open edX credentials multiple times, but every time a verifiable credential is issued,
How do we think about vc versus presentation here?  Would we consider a single VC per subject/claim, but multiple presentations?

2022-12-12 16:06 UTC, e0d commented on docs/decisions/0008-issue-verifiable-credentails-in-learner-records-mfe.rst
> +* The MFE should determine the user's device type, whether it is a desktop or mobile device. If the user opens verifiable credentials interface from desktop, the QR Code generated on a server should
Would we provide access to the alternative as a fall back link?

2023-01-19 22:14 UTC, GlugovGrGlib commented on docs/decisions/0007-verifiable-credentials-issuing.rst
> +* implement integrations with different verifiable credentials singing services, such as `SpruceID's didkit-python`_, `DCC's sign-and-verify`_, and other open-source and proprietary solutions.
Thanks for correcting the typo, the first version is pretty funny if to think about it

2023-02-22 17:44 UTC, mphilbrick211 commented
@GlugovGrGlib friendly follow-up on this :)

2023-02-27 17:22 UTC, e0d approved these changes

2023-08-01 18:24 UTC, merged