fix: added Makefile target to run tests with Karma
openedx/credentials pull request #1851
Opened 2022-12-06 19:29 UTC by MaxFrank13

This adds a new Makefile target that will install Firefox and run the tests using Karma. There is also a PR template that will remind future contributors to run these tests locally. Once a fix is found for getting these tests to run in CI, we will need to remove this PR template.

2022-12-07 15:10 UTC, justinhynes requested changes
Good stuff! One requested change before accepting this change. Let me know if you have any questions!

2022-12-07 15:10 UTC, justinhynes commented on Makefile
> +	sudo apt-get install --no-install-recommends -y firefox
Just in case, I would also add a line before this to update the package information for all the configured sources.

So, before the `sudo apt-get install...` line, add `sudo apt-get update`

2022-12-07 15:10 UTC, justinhynes commented on Makefile
> +	sudo apt-get install --no-install-recommends -y firefox
I think in the original CI workflow we were also installing `xvfb`. Maybe we should also include that package to cover our bases?

2022-12-07 18:45 UTC, MaxFrank13 commented on Makefile
> +	sudo apt-get install --no-install-recommends -y firefox
Good call! The command now installs `xvfb` and then uses `xvfb-run` similar to [how it's done here](https://github.com/openedx/edx-custom-a11y-rules/blob/86bd06bfdaaead4be81a3b46b0833b29add46362/.github/workflows/ci.yml#L34)

2022-12-08 14:50 UTC, justinhynes approved these changes

2022-12-13 15:50 UTC, merged