feat: Course completion endpoint
openedx/credentials pull request #1988
Opened 2023-04-18 17:55 UTC by cdeery

WIP: This is a first pass at an API to show the status for a learner of their course certificates. I am posting it for the Ponderosa team to be able to take a look at the inputs and outputs and evaluate the functionality.

**Run JavaScript tests locally with Karma**

There is work being done on a fix to get Karma to run in CI. Until then, however, contributors are required to run these tests locally.

- [ ] Make sure you are inside the devstack container
- [ ] Run `make test-karma`
- [ ] All tests pass

2023-04-28 15:31 UTC, cdeery commented on credentials/apps/credentials/rest_api/v1/permissions.py
> +class UserCredentialViewSetPermissions(permissions.DjangoModelPermissions):
No, that was just a placeholder. The actual permissions will be forthcoming shortly

2023-04-28 15:31 UTC, cdeery commented on credentials/apps/credentials/rest_api/v1/views.py
> +    permission_classes = (permissions.IsAdminUser,)
Yes, that will be in the next push.

2023-05-03 14:20 UTC, justinhynes commented on credentials/settings/base.py
> +LEARNER_STATUS_WORKER = "replace with valid username"
nit: Is this worker tied to an IDA by any chance? Is this request coming from the Subscriptions IDA? If so, maybe we can make a stronger association of the name of the worker to the source of the request? (`SUBSCRIPTIONS_WORKER`?)

2023-05-03 15:25 UTC, justinhynes commented on credentials/apps/credentials/rest_api/v1/views.py
> +            # we don't have the user in the system
Do you think it would be useful to log something here in this case?

2023-05-03 15:30 UTC, justinhynes commented on credentials/apps/credentials/rest_api/v1/views.py
> +        uuids and/or a program uuid.
General question: According to this comment we _could_ receive a Program UUID. What happens in that case? Nothing? It seems like we're only returning information around the learner's statuses in their courses. 

I see that we're getting back some program credential information from our call to `get_credentials` (on line 101) but we're not doing anything with `program_credentials` returned. Is this future work? Fast follow? Or a mistake in the docstring?

2023-05-03 15:34 UTC, justinhynes commented on credentials/apps/credentials/rest_api/v1/views.py
> +from credentials.apps.records.models import UserGrade
We really shouldn't be importing models from other apps directly. If there is a requirement to retrieve grade information we should use (or create) a Python API function from the `records` Django app.

Utility functions that live inside a Django app's `api.py` file are considered public and exposed for general use across Django apps.

2023-05-03 15:35 UTC, justinhynes commented on credentials/apps/credentials/rest_api/v1/views.py
> +from credentials.apps.records.utils import get_credentials
Similarly, we shouldn't be importing and using utility functions from another Django app unless they are inside of the app's `api.py` file. If we need to call `get_credentials` from another Django app, we should have a "public" wrapper for the utility in the app's `api.py` file.

2023-05-03 15:38 UTC, justinhynes requested changes
Could we try and reduce/remove the use of cross-app Model imports and internal utility functions? TIA! Let me know if you have any questions.

2023-05-03 15:40 UTC, cdeery commented on credentials/apps/credentials/rest_api/v1/views.py
> +        uuids and/or a program uuid.
That is planned for a fast follow- I will spell it out more in the ADR, but being able to sanity check a learner's status against a particular program will help Aperture and support.

2023-05-03 15:42 UTC, justinhynes commented on credentials/apps/credentials/rest_api/v1/views.py
> +from credentials.apps.records.utils import get_credentials
(optionally) we could just move the function to the public `api.py` too, but I'm unsure how many references would need to be updated at that point

2023-05-03 18:44 UTC, cdeery commented on credentials/apps/credentials/rest_api/v1/views.py
> +            # we don't have the user in the system
Yes, that's a good idea. Will do

2023-05-03 18:52 UTC, cdeery commented on credentials/apps/credentials/rest_api/v1/views.py
> +from credentials.apps.core.models import User
Thanks. Will do.

2023-05-04 23:29 UTC, cdeery commented on credentials/settings/base.py
> +LEARNER_STATUS_WORKER = "replace with valid username"
I think it's better to have the user identified by the right they have rather than the current job, as the API may be used for other use cases in the future. I'm open to hashing out better names.

2023-05-04 23:36 UTC, cdeery commented on credentials/apps/credentials/rest_api/v1/views.py
> +from credentials.apps.records.models import UserGrade
Thanks. Refactored code to eliminate cross-app includes

2023-05-04 23:37 UTC, cdeery commented on credentials/apps/credentials/rest_api/v1/views.py
> +from credentials.apps.records.utils import get_credentials
I created an internal API to handle the private information.

2023-05-04 23:47 UTC, cdeery commented
@shafqatfarhan do you have any additional comments?

2023-05-08 14:41 UTC, justinhynes commented on credentials/apps/credentials/rest_api/v1/views.py
> +            # we don't have the user in the system
Thanks!

2023-05-08 14:47 UTC, justinhynes approved these changes
Thanks for making the suggested changes!

2023-05-08 14:50 UTC, merged