feat: add decorator that can be used to log incoming REST request data
openedx/credentials pull request #2364
Opened 2024-01-26 19:32 UTC by justinhynes

[APER-3122]

Adds a decorator that can be used to log incoming REST request data. This will be used to get more visibility into the grade updates flowing from the LMS to Credentials.

This functionality will be gated using a WaffleSwitch so that we don't cause a massive spike in log size. This is intended to be used for debugging when needed.

**Run JavaScript tests locally with Karma**

There is work being done on a fix to get Karma to run in CI. Until then, however, contributors are required to run these tests locally.

- [ ] Make sure you are inside the devstack container
- [ ] Run `make test-karma`
- [ ] All tests pass

2024-01-26 20:16 UTC, justinhynes commented on credentials/apps/api/v2/decorators.py
> +TODO
YEESH. I forgot to fill this in. I'll take care of this before a final merge.

2024-01-26 20:17 UTC, justinhynes commented on credentials/settings/base.py
> +# .. toggle_description: Toggle to control whether we log incoming REST requests through the use of the `log_request`
Just realized the name of the decorator here is incorrect. Will fix.

2024-01-26 20:24 UTC, deborahgu requested changes
a couple of minor things, plus the code coverage report, but looks really nice. I love the waffle switch. I really do want to raise a greater conversation about putting debug logging  behind a waffle switch; I think that could be super valuable, at least in a smaller IDA like credentials. In edx-platform we would probably drown, lol.

2024-01-26 20:24 UTC, deborahgu commented on credentials/apps/api/v2/decorators.py
> +TODO
probably you intend to change that

2024-01-26 20:24 UTC, deborahgu commented on credentials/apps/api/v2/decorators.py
> +LOGGER = logging.getLogger(__name__)
I've noticed this in some of our older code, but we shouldn't be allcapsing python variables, unless there is some style guide you are following here that I haven't seen or have expunged from my memory to save sanity points.

2024-01-26 20:24 UTC, deborahgu commented on credentials/apps/api/v2/decorators.py
> +    decorator, we don't want to accidentally log any secrets or sensitive PII.
🎉

2024-01-29 15:00 UTC, justinhynes commented on credentials/apps/api/v2/decorators.py
> +TODO
Fixed!

2024-01-29 15:00 UTC, justinhynes commented on credentials/settings/base.py
> +# .. toggle_description: Toggle to control whether we log incoming REST requests through the use of the `log_request`
Fixed!

2024-01-29 15:00 UTC, justinhynes commented on credentials/apps/api/v2/decorators.py
> +TODO
Yepppp! Thanks, fixed in an update being pushed shortly.

2024-01-29 18:38 UTC, merged