feat: add badges feature
openedx/credentials pull request #2489
Opened 2024-05-24 18:52 UTC by kyrylo-kh

**Description:**
This pull request implements [Credly integration](https://github.com/openedx/platform-roadmap/issues/280) feature.

**Changes:**
- Creates new `badges` application.
- Extends documentation with `badges` section.
- Extends set of credentials

**Related documentation:**
See temporarily deployed documentation https://raccoongang.github.io/credentials/badges/index.html

**Related PR's:**
- https://github.com/openedx/openedx-events/pull/303
- https://github.com/openedx/edx-platform/pull/34749

2024-06-03 13:12 UTC, wowkalucky requested changes

2024-06-03 13:12 UTC, wowkalucky commented on credentials/apps/badges/models.py
> +    def groups(self):
Docsting.

2024-06-03 13:12 UTC, wowkalucky commented on credentials/apps/badges/models.py
> +    def is_active(self):
Docstring.

2024-06-03 13:12 UTC, wowkalucky commented on credentials/apps/badges/models.py
> +    def groups(self):
Docstring.

2024-06-03 13:12 UTC, wowkalucky commented on credentials/apps/badges/models.py
> +    def reset(self):
Docstring.

2024-06-03 13:12 UTC, wowkalucky commented on credentials/settings/production.py
> +add_plugins(__name__, PROJECT_TYPE, SettingsType.PRODUCTION)
This must be added instead of the line #67 (remove the last line).

2024-06-03 13:12 UTC, wowkalucky commented on docs/badges/index.rst
> +Badges
Documentation:
- remove not relevant images
  - docs/_static/images/badges/badges-award-sequence.png
  - docs/_static/images/badges/badges-revoke-sequence.png
  - docs/_static/images/badges/badges-setup-sequence.png

2024-06-04 10:20 UTC, kyrylo-kh commented
@wowkalucky @GlugovGrGlib please review this PR

2024-06-06 10:54 UTC, GlugovGrGlib commented on credentials/apps/credentials/migrations/0026_alter_usercredential_credential_content_type.py
> +            field=models.ForeignKey(limit_choices_to={'model__in': ('coursecertificate', 'programcertificate', 'badgetemplate')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.content
@kyrylo-kh This migration should be squashed

2024-06-06 10:57 UTC, GlugovGrGlib commented on credentials/apps/credentials/migrations/0029_merge_20240527_1017.py
> +    dependencies = [
I believe we can get rid of this migration in case migrations are squashed

2024-06-06 11:00 UTC, GlugovGrGlib commented on credentials/settings/base.py
> +    # these events become available in rules setup:
```suggestion
    # list of the events that should be available in rules configuration interface:
```

2024-06-06 11:12 UTC, GlugovGrGlib commented on credentials/settings/base.py
> +BADGES_CONFIG = {
If the badges application is a plugin itself, maybe we can move `BADGES_CONFIG` into the plugin_settings?

2024-06-10 09:57 UTC, GlugovGrGlib commented on credentials/apps/badges/apps.py
> +    plugin_label = "badges"
Plugin label seems to be redundant in this case

2024-06-12 09:47 UTC, wowkalucky commented on credentials/apps/badges/apps.py
> +        Activate installed badges plugins if they are enabled.
Pls, remove this line as well.

2024-06-12 09:47 UTC, wowkalucky commented on credentials/settings/base.py
> +BADGES_ENABLED = True
This is expected to be disabled by default.

2024-06-12 09:47 UTC, wowkalucky commented on requirements/base.in
> +git+https://github.com/openedx/event-bus-redis.git@v0.4.0
There is already [0.5.0](https://github.com/openedx/event-bus-redis/releases/tag/v0.5.0)

2024-06-17 22:13 UTC, GlugovGrGlib approved these changes

2024-06-18 14:07 UTC, justinhynes commented
Just dropping a line to say I'm starting my review this morning.

2024-06-18 14:12 UTC, justinhynes commented on .annotation_safe_list.yml
> +  ".. pii_types": other
nit: If I understand the markup correctly, the "pii_type" here should be `username` , with `pii` being a description (and somewhat redundant". 

The `pii_type`'s referenced in [OEP-30](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0030-arch-pii-markup-and-auditing.html) are...
```
name (used for any part of the user’s name)
username
password
location (used for any part of any type address or country stored)
phone_number (used for phone or fax numbers)
email_address
birth_date (used for any part of a stored birth date)
ip (IP address)
external_service (used for external service ids or links such as social media links or usernames, website links, etc)
biography (any type of free-form biography field)
gender
sex
image
video
other (any identifying information not covered by other types, should be specified in the pii annotation)
```

2024-06-18 14:14 UTC, justinhynes commented on .annotation_safe_list.yml
> +  ".. pii_retirement": retained
Is the ntent to retain this info for credential verification after a learner potentially deletes their account?

2024-06-18 14:20 UTC, justinhynes commented on credentials/apps/badges/admin.py
> +    def has_add_permission(self, request):
Curious: Should this always return false?

Assumption: We have some sync process adding the templates? Which can be viewed (and maybe modified?) but never directly added via Django admin?

2024-06-18 14:25 UTC, justinhynes commented on credentials/apps/badges/admin_forms.py
> +        self.fields["blend"].choices = Choices(*[(chr(i), chr(i)) for i in range(65, 91)])
Just curious about this as it seems so oddly specific. Can you tell me more? What is "blend" in this context? Is this a property of a BadgeRequirement?

2024-06-18 14:27 UTC, justinhynes commented on credentials/apps/badges/apps.py
> +        from credentials.apps.badges import signals  # pylint: disable=unused-import,import-outside-toplevel
Why do we need the imports inside the function?

2024-06-18 14:28 UTC, justinhynes commented on credentials/apps/badges/checks.py
> +                id="badges.E001",
Should the error content be localized? or localizable? Seems like it might be hardcoded English here.

2024-06-18 15:24 UTC, justinhynes commented on credentials/apps/badges/credly/api_client.py
> +        return self.perform_request("get", f"badge_templates/?filter=state::{CredlyBadgeTemplate.STATES.active}")
I am curious if the recent changes in Python 3.11 and f-strings will affect this line of code. Is `STATES` an enum? 

(Reference to change: https://github.com/python/cpython/issues/100458)

2024-06-18 15:25 UTC, justinhynes commented on credentials/apps/badges/credly/api_client.py
> +        return len(raw_badge_templates)
Can we write a unit test for this functionality?

2024-06-18 15:28 UTC, justinhynes commented on credentials/apps/badges/credly/data.py
> +    issued_to_last_name: str
I know names can be tricky. Is first_name/last_name a restriction imposed by Credly?

2024-06-18 15:36 UTC, justinhynes commented on credentials/apps/badges/credly/webhooks.py
> +            logger.error(f"Unknown event type: {event_type}")
Should we be coding defensively if, for some chance `event_type` is not able to be retrieved?
```
event_type = request.data.get("event_type")

if event_type and event_type == "bade_template.created":
    blah
, or,
if event_type:
    if event_type == "blah":
        blah
```

2024-06-18 20:02 UTC, justinhynes commented on credentials/apps/badges/credly/data.py
> +    issued_to_last_name: str
Additional context: I'm asking because I thought Django was moving towards "Full name" and I think our user table was updated to capture "Full name". I know that not everyones names fit neat and tidy into a "first name" and "last name" breakdown. Mostly curious.

2024-06-20 12:21 UTC, justinhynes commented on credentials/apps/badges/management/commands/sync_organization_badge_templates.py
> +import logging
Are there any unit tests for the management command?

2024-06-20 12:29 UTC, justinhynes commented on credentials/apps/badges/models.py
> +            self.save(*args, **kwargs)
Curious about this piece? Why do we need an overridden save() function here?

2024-06-20 12:55 UTC, justinhynes commented on credentials/apps/badges/models.py
> +        return f"{credly_host_base_url}mgmt/organizations/{self.organization.uuid}/badges/templates/{self.uuid}/details"
Would `urljoin` be helpful here to protect against a potentially poorly defined `credly_host_base_url` in settings? (thinking of someone forgetting to add a `/` to the end of `credly_host_base_url`)

2024-06-20 12:59 UTC, justinhynes commented on credentials/apps/badges/models.py
> +    EVENT_TYPES = Choices(*settings.BADGES_CONFIG["events"])
Can we expect the `events` in the config to ever change? If so, how would the `EVENT_TYPES` here get updated?

2024-06-20 13:15 UTC, justinhynes commented on credentials/apps/badges/models.py
> +        deleted, __ = fulfillment.delete() if fulfillment else (False, 0)
Nit: Personally, I'm not a fan of ternary operators and find the long form much more readable/maintainable. Would prefer to see this rewritten but not going to block on it.

At the very least, I find it a bit unintuitive that the value, if false, returns the tuple (False,0). Why?

2024-06-20 13:17 UTC, justinhynes commented on credentials/apps/badges/models.py
> +        # ('gt', '>'),
Are these intended to be commented out? Can we remove them if they aren't needed?

2024-06-20 13:21 UTC, justinhynes commented on credentials/apps/badges/models.py
> +    username = models.CharField(max_length=255)  # index
What is the `index` comment here? Did we intend to add a db index for this field? If so, do we still need to (I think this generates an additional migration if so?). If not, should we remove this comment?

2024-06-20 13:26 UTC, justinhynes commented on credentials/apps/badges/models.py
> +        return round(true_values / len(self.groups.keys()), 2)
As someone who has very little understanding of Badges in general, I find these two lines a bit complex. Do we need any additional comments? What does "x" represent? Is this calculating a specific user/learner's progress towards a badge? 

I just know that my eyes start to swim after seeing `(len(list(fliter(lambda: blah)))` and feel like some more comments/context might make this more readable/grokable by future maintainers.

2024-06-20 13:35 UTC, wowkalucky commented on .annotation_safe_list.yml
> +  ".. pii_retirement": retained
Users' retirement aspect was completely out of focus during the scope development. 
But, we should treat badges as other user credentials (so the same approach as for certificates should fit).
Not implemented though.

2024-06-20 13:39 UTC, wowkalucky commented on credentials/apps/badges/admin_forms.py
> +        self.fields["blend"].choices = Choices(*[(chr(i), chr(i)) for i in range(65, 91)])
So long story short: on the final checks we figured out that `group` attribute is clashing with some Django internals, so we updated it to `blend`.

The idea behind the `blend` is to group badge requirements, so they are processed by "OR" logic (by default ALL badge requirements must be fulfilled).

2024-06-20 17:45 UTC, wowkalucky commented on credentials/apps/badges/apps.py
> +        from credentials.apps.badges import signals  # pylint: disable=unused-import,import-outside-toplevel
We want to register the application's signals and checks, but be sure that Django models are initiated already.

2024-06-20 17:48 UTC, wowkalucky commented on credentials/apps/badges/credly/api_client.py
> +            organization_id (str, uuid): ID of the organization.
I believe it expects a string formatted as UUID (but not a UUID object).

2024-06-21 09:53 UTC, wowkalucky commented on credentials/apps/badges/models.py
> +            self.save(*args, **kwargs)
This artifact is from the initial intention to support multiple badge providers (where `origin` identifies a provider). Possibly, we need to simplify it now.

2024-06-21 09:56 UTC, wowkalucky commented on credentials/apps/badges/credly/data.py
> +    issued_to_last_name: str
Yeah, this data shape describes what is expected by the Credly API.

2024-06-21 11:56 UTC, justinhynes commented on credentials/apps/badges/processing/generic.py
> +        return
Should there be a warning here, or some sort of logged message? Any chance we're missing a chance to log some important bit of context or info?

2024-06-21 11:58 UTC, justinhynes commented on credentials/apps/badges/processing/generic.py
> +        **kwargs: public event keyword arguments containing user identification data.
I don't see `kwargs` as part of the function signature, and `event_type` and `event_payload` are missing. Is this correct?

2024-06-21 12:35 UTC, justinhynes commented on credentials/apps/badges/processing/progression.py
> +            continue
Are these TODO's still outstanding? Can the comment be removed? Is this captured by other work/tickets?

2024-06-21 12:41 UTC, justinhynes commented on credentials/apps/badges/tests/test_admin_forms.py
> +    pass
Were there supposed to be any tests here?

2024-06-21 12:51 UTC, justinhynes commented on credentials/apps/badges/tests/test_services.py
> +        self.CCX_COURSE_PASSING_EVENT = "org.openedx.learning.ccx.course.passing.status.updated.v1"
Tangentially related question: CCX courses have not been eligible for certificates. 

Is a badge considered equivalent to a certificate issued by an Open edX instance? 

I'm half worried about a CCX + credly being able to issue a credential to a learner, where that has been explicitly not allowed for a traditional CCX.

2024-06-21 12:51 UTC, justinhynes commented on credentials/apps/badges/tests/test_services.py
> +        self.CCX_COURSE_PASSING_EVENT = "org.openedx.learning.ccx.course.passing.status.updated.v1"
blocking question for the review, more for my own edification.

2024-06-21 12:53 UTC, justinhynes commented on credentials/apps/badges/tests/test_services.py
> +    #     (A or B) and (C or D) - courses A, B have the same group value; courses C, D have the same group value;
nit: I would love for this to end up as a docstring for each test case, explaining what the test case is designed to check for. 

Otherwise, this is still great. Some context is better than no context. :)

2024-06-21 12:55 UTC, justinhynes commented on credentials/apps/badges/tests/test_services.py
> +        BADGE_PROGRESS_COMPLETE.connect(handle_badge_completion)
Nit: Can we move this under the `setUp` function? I find test classes are much easier to grok when they generally follow the same flow of...

class blah(TestCase):
  def setUpClass()
  def setUp()
  def tearDown()
  def tearDownClass()
  {test utility function}
  {test cases}

2024-06-21 12:58 UTC, justinhynes commented on credentials/apps/badges/tests/test_webhooks.py
> +    return "test"
Is this used?

2024-06-21 13:09 UTC, justinhynes commented on docs/badges/configuration.rst
> +In case of errors check the used credentials for the Organization.
Nit: "In case of errors, check the credentials used for the Organization"

2024-06-21 13:11 UTC, justinhynes commented on docs/badges/configuration.rst
> +2. to set the authorization token issue one in the Credly Organization's dashboard.
Nit: I think this needs to be reworded. I'm not sure what it's trying to tell me to do. 

"to set the authorization token, used to sync the Credly Organization"?

2024-06-21 13:18 UTC, justinhynes commented on docs/badges/configuration.rst
> +external platform will not be aware of any changes so it might continue issuing outdated badges.
Nit: Reword suggestion, feel free to ignore.
```
Webhooks are configured in Credly in order to inform external systems (e.g. the Credentials IDA) when an important action has occurred. 

You should be able to select an action from the list so that whenever the specified action occurs internally, the external system is alerted.

Without this synchronization, the external system will not be notified of any significant changes (e.g. a badge template update, or a badge template has been archived) and may incorrectly issue erroneous or outdated badges.
```

2024-06-21 13:24 UTC, justinhynes commented on docs/badges/configuration.rst
> +A badge template can can have multiple requirements. All badge requirements must be *fulfilled* to earn a badge.
The word `can` is here twice. We can remove one of them. :)

Nit: Another reword suggestion: "A badge template can have multiple requirements. All badge requirements must be fulfilled before the system will issue a badge to a learner."

2024-06-21 13:26 UTC, justinhynes commented on docs/badges/configuration.rst
> +    "OR" logic is applied inside a Group.
Do you think it would be helpful to link to any Credly docs here?

2024-06-21 13:31 UTC, justinhynes commented on docs/badges/configuration.rst
> +When a penalty has worked all linked badge requirements are "rolled back" (user's progress for such requirements is reset).
Nit: Maybe we can reword this a bit to make it clearer? 
```
When a penalty has been processed (detected? received?), a learner's progress towards a badge is reset.
```

2024-06-21 13:39 UTC, justinhynes commented on docs/badges/index.rst
> +    **Credly** is the end-to-end solution for creating, issuing, and managing digital credentials. Thousands of organizations use **Credly** to recognize achievement.
Nit: Suggest a reword to something like... `**Credly** is a end-to-end solution for creating, issuing, and managing digital Credentials. Organizations use **Credly** to recognize their learners' achievements.`

I know this is most likely copied and pasted from Credly docs or their website, but it feels like marketing jargon in the Open edX docs.

2024-06-21 13:41 UTC, justinhynes commented on docs/badges/processing.rst
> +Badge revoking is optional. Business needs. Configuration. And why.
Nit: `Business needs. Configuration. And why.` I'm unsure what this is trying to tell me.

2024-06-21 13:42 UTC, justinhynes commented on docs/badges/processing.rst
> +Badge revoking is optional. Business needs. Configuration. And why.
Was this sentence intended to be a TODO that should have been removed?

2024-06-21 13:48 UTC, justinhynes commented on docs/badges/processing.rst
> +When system revokes a badge, the status of a badge will change from awarded to revoked in the admin panel (admim/badges/credly_badges) as the revoke process is synced with external platform.
Nit: Is the admin panel here talking about Credly? Or the Credentials IDA's Django admin panel? I'm also not sure what "system" we're talking about? Is this the Credentials IDA? or Credly? 

I think we can reword this to make it a bit clearer: 
"When a learner's badge is revoked by Credly(?), the Credentials IDA will be notified and will update it's internal records. The status of the badge will change from `awarded` to `revoked` upon successful revocation."

2024-07-02 09:40 UTC, wowkalucky commented on credentials/apps/badges/credly/api_client.py
> +        return len(raw_badge_templates)
Ok, we'll cover this with tests.

2024-07-02 09:40 UTC, wowkalucky commented on credentials/apps/badges/issuers.py
> +        user_credential.save()
Ok, got it.

2024-07-02 09:41 UTC, wowkalucky commented on credentials/apps/badges/management/commands/sync_organization_badge_templates.py
> +import logging
Ok, added to testing.

2024-07-02 09:43 UTC, wowkalucky commented on credentials/apps/badges/models.py
> +    icon = models.ImageField(upload_to="badge_templates/icons", null=True, blank=True)
I'm not sure I'm getting the request here. Can you elaborate more?

2024-07-02 09:46 UTC, wowkalucky commented on credentials/apps/badges/models.py
> +            self.save(*args, **kwargs)
Since we have implemented a hierarchy of badge templates (CredlyBadgeTemplate(BadgeTemplate)), each class (model) has it's own badge template "type" - ORIGIN. So it is possible to distinguish the nature of a badge template. Currently, we are using CredlyBadgeTemplate exclusively.

2024-07-02 09:46 UTC, wowkalucky commented on credentials/apps/badges/models.py
> +        return f"{credly_host_base_url}mgmt/organizations/{self.organization.uuid}/badges/templates/{self.uuid}/details"
Definitely.

2024-07-02 09:49 UTC, wowkalucky commented on credentials/apps/badges/models.py
> +    EVENT_TYPES = Choices(*settings.BADGES_CONFIG["events"])
Events configuration can be overridden from deployment envs, but it won't change during the runtime.

2024-07-02 09:50 UTC, wowkalucky commented on credentials/apps/badges/models.py
> +        deleted, __ = fulfillment.delete() if fulfillment else (False, 0)
Ok. Let's extract it.

2024-07-02 09:51 UTC, wowkalucky commented on credentials/apps/badges/models.py
> +        # ('gt', '>'),
Let's remove these.

2024-07-02 09:51 UTC, wowkalucky commented on credentials/apps/badges/models.py
> +    username = models.CharField(max_length=255)  # index
Ok, we'll clean this.

2024-07-02 09:54 UTC, wowkalucky commented on credentials/apps/badges/models.py
> +        return round(true_values / len(self.groups.keys()), 2)
@kyrylo-kh  Let's make it more verbose. Pls comment on it and possibly, unfold a bit.

2024-07-02 09:56 UTC, wowkalucky commented on credentials/apps/badges/processing/generic.py
> +        return
@kyrylo-kh pls, double check if we use this logical exception at all. If it is used, pls. add debug logging here.

2024-07-02 09:57 UTC, wowkalucky commented on credentials/apps/badges/processing/generic.py
> +        **kwargs: public event keyword arguments containing user identification data.
@kyrylo-kh pls clarify in the comment here.

2024-07-02 09:58 UTC, wowkalucky commented on credentials/apps/badges/processing/progression.py
> +            continue
@kyrylo-kh let's just remove these comments for now.

2024-07-02 10:00 UTC, wowkalucky commented on credentials/apps/badges/tests/test_admin_forms.py
> +    pass
We've added this intermediary class for verbosity to stress the testing purpose.

2024-07-02 14:52 UTC, justinhynes commented on credentials/apps/badges/models.py
> +    icon = models.ImageField(upload_to="badge_templates/icons", null=True, blank=True)
Sure, sorry if the question was unclear. 

So it looks like we'll be storing an Icon as part of Credentials data and this model. Is there any additional configuration needed to be able to store these files in Credentials? If so, is this setup documented anywhere?

Or is Credentials (or Tutor) already configured to handle asset storage out of the box? 

I was trying to determine if there is any additional configuration or settings updates required if someone wanted to use Badges.

Let me know if it's still unclear :)

2024-07-05 09:42 UTC, wowkalucky commented on docs/badges/configuration.rst
> +When a penalty has worked all linked badge requirements are "rolled back" (user's progress for such requirements is reset).
@andrii-hantkovskyi let's do like this:
```
When all penalty rules have been applied, a learner's progress towards a badge is reset.
```

2024-07-05 09:44 UTC, wowkalucky commented on docs/badges/configuration.rst
> +    "OR" logic is applied inside a Group.
@justinhynes it's not related to the Credly in any way. This is a completely internal processing logic implementation.

2024-07-05 09:50 UTC, wowkalucky commented on docs/badges/configuration.rst
> +For the usage a badge template must be configured and activated first.
So, the Credentials Badges feature operates exclusively on Credly-ready (configured on the Credly side) badge templates.
To use (start their processing) such synced badge templates one must:
1. set it's requirements 
2. enable it

My suggestion for improvement here could be:

```
For a badge template to be considered during the processing it must be configured (to have at least 1 requirement) and activated (enabled) first.
```

2024-07-08 19:06 UTC, GlugovGrGlib commented
Hi @justinhynes, thank you so much for your review! We have addressed all the comments, would you be able to do the final round of review this week?

2024-07-10 11:02 UTC, andrii-hantkovskyi commented
@justinhynes Hi, just wanted to thank you for your remarks. We have gone through all of them and given appropriate responses where no fixes needed. All relevant problems have been fixed. Kindly look at the code again when time allows you to do so :)

2024-07-17 12:32 UTC, justinhynes commented
Hi @andrii-hantkovskyi. Apologies, I missed your last update until today. 

I will block out some time to re-review. Thanks for the heads up :)

2024-07-18 12:20 UTC, justinhynes approved these changes
This looks good to me. Thanks for the clarifications and updates. Lastly, a huge thanks to the team for 1) wanting us to to take a look in the first place, and 2) all the patience for us to review (and re-review).

2024-07-22 14:44 UTC, merged

2024-07-22 14:44 UTC, openedx-webhooks commented
@kyrylo-kh 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/credentials&entry.867055334=https://github.com/openedx/credentials/pull/2489&entry.1484655318=https://github.com/kyrylo-kh&entry.752974735=2024-05-24+18:52&entry.1917517419=2024-07-22+14:44&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->